version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cocktail-db-prod"
s3_bucket = "cocktail-db-prod-deployment"
s3_prefix = "cocktail-db-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Environment=prod DatabaseName=cocktaildb" 