AWSTemplateFormatVersion: '2010-09-09'
Description: CocktailDB Shared AWS Resources (Cognito, S3, IAM, DNS)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The deployment environment (dev or prod).
  DomainName:
    Type: String
    Default: mixology.tools
    Description: Custom domain name for production (e.g., mixology.tools). Not used for dev.
  HostedZoneId:
    Type: String
    Default: ""
    Description: ID of the existing Route 53 hosted zone for your production domain. Required if Environment is prod.
  EC2ElasticIP:
    Type: String
    Default: ""
    Description: Elastic IP address of the EC2 instance (required for prod).
  AuthSubdomain:
    Type: String
    Default: auth
    Description: Subdomain for Cognito authentication (e.g., 'auth' creates auth.mixology.tools)
  AuthCertificateArn:
    Type: String
    Default: ""
    Description: ARN of the ACM certificate for the auth subdomain (must be in us-east-1). Required if Environment is prod.
  CognitoAdvancedSecurity:
    Type: String
    Default: "OFF"
    Description: Cognito advanced security mode (OFF for dev, ENFORCED for prod)
  UserPoolName:
    Type: String
    Default: "CocktailDB-UserPool-dev"
  GoogleClientId:
    Type: String
    Default: ""
    Description: Google OAuth Client ID for social login (optional)
  GoogleClientSecret:
    Type: String
    Default: ""
    Description: Google OAuth Client Secret for social login (optional)
    NoEcho: true
  AmazonClientId:
    Type: String
    Default: ""
    Description: Amazon Client ID for Login with Amazon (optional)
  AmazonClientSecret:
    Type: String
    Default: ""
    Description: Amazon Client Secret for Login with Amazon (optional)
    NoEcho: true

Conditions:
  IsProdEnvironment: !Equals [!Ref Environment, "prod"]
  IsDevEnvironment: !Not [!Equals [!Ref Environment, "prod"]]
  HasGoogleOAuth: !Not [!Equals [!Ref GoogleClientId, ""]]
  HasAmazonOAuth: !Not [!Equals [!Ref AmazonClientId, ""]]

Resources:
  # =============================================================================
  # S3 Buckets
  # =============================================================================

  # S3 bucket for database backups (prod only)
  BackupBucket:
    Type: AWS::S3::Bucket
    Condition: IsProdEnvironment
    Properties:
      # Let CloudFormation generate unique name to avoid conflicts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldBackups
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: database-backups

  # =============================================================================
  # IAM - EC2 Role and Instance Profile
  # =============================================================================
  # NOTE: For prod, IAM resources are managed by the separate cocktaildb-prod-ec2
  # CloudFormation stack (infrastructure/cloudformation/ec2-iam.yaml) which also
  # manages the Elastic IP. This allows the EC2 instance to be managed independently.
  #
  # For dev, we create the IAM resources here since there's no separate EC2 stack.

  # IAM Role for EC2 instances - dev only
  EC2Role:
    Type: AWS::IAM::Role
    Condition: IsDevEnvironment
    Properties:
      RoleName: !Sub cocktaildb-${Environment}-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

  # Instance Profile for EC2 - dev only
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: IsDevEnvironment
    Properties:
      InstanceProfileName: !Sub cocktaildb-${Environment}-ec2-profile
      Roles:
        - !Ref EC2Role

  # =============================================================================
  # Cognito User Pool and Authentication
  # =============================================================================

  CognitoUserPoolV3:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      UserPoolAddOns:
        AdvancedSecurityMode: !Ref CognitoAdvancedSecurity
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: preferred_username
          AttributeDataType: String
          Required: false
          Mutable: false

  CognitoUserPoolV3Client:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      ClientName: !Sub cocktaildb-client-${Environment}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 4
      IdTokenValidity: 4
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      CallbackURLs: !If
        - IsProdEnvironment
        - - !Sub "https://${DomainName}/callback.html"
          - !Sub "https://${DomainName}/login.html"
        - - "http://localhost:8000/callback.html"
          - "http://localhost:8000/login.html"
          - !Sub "https://dev.${DomainName}/callback.html"
          - !Sub "https://dev.${DomainName}/login.html"
      LogoutURLs: !If
        - IsProdEnvironment
        - - !Sub "https://${DomainName}/logout.html"
        - - "http://localhost:8000/logout.html"
          - !Sub "https://dev.${DomainName}/logout.html"
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      WriteAttributes:
        - email
      ReadAttributes:
        - email

  # Cognito User Pool Groups
  CognitoAdminGroupV3:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      GroupName: admin
      Description: System administrators with full access
      Precedence: 1

  CognitoEditorGroupV3:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      GroupName: editor
      Description: Content editors - can create, edit, and delete recipes and ingredients
      Precedence: 2

  # Cognito Domain for Hosted UI
  CognitoDomainV3:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !If
        - IsProdEnvironment
        - !Sub "${AuthSubdomain}.${DomainName}"
        - !Sub "cocktaildbauth-${Environment}-${AWS::AccountId}-v3"
      UserPoolId: !Ref CognitoUserPoolV3
      CustomDomainConfig: !If
        - IsProdEnvironment
        - CertificateArn: !Ref AuthCertificateArn
        - !Ref "AWS::NoValue"

  # UI Customization for Cognito Hosted UI
  CognitoUICustomizationV3:
    Type: AWS::Cognito::UserPoolUICustomizationAttachment
    DependsOn: CognitoDomainV3
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      ClientId: !Ref CognitoUserPoolV3Client
      CSS: |
        .background-customizable { background-color: #f5f5f5 !important; }
        .banner-customizable { background-color: #2c3e50 !important; padding: 1.5rem 2rem !important; }
        .logo-customizable { display: none !important; }
        .textDescription-customizable { color: white !important; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important; font-size: 1.4rem !important; font-weight: 600 !important; }
        .inputField-customizable { width: 100% !important; padding: 0.75rem !important; border: 1px solid #ddd !important; border-radius: 4px !important; font-size: 1rem !important; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important; background-color: #fff !important; color: #333 !important; }
        .inputField-customizable:focus { border-color: #A61816 !important; box-shadow: 0 0 0 2px rgba(166, 24, 22, 0.1) !important; outline: none !important; }
        .label-customizable { color: #333 !important; font-weight: bold !important; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important; margin-bottom: 0.5rem !important; display: block !important; }
        .submitButton-customizable { background-color: #A61816 !important; border-color: #A61816 !important; color: white !important; padding: 0.75rem 1.5rem !important; border-radius: 4px !important; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important; font-size: 1rem !important; font-weight: 500 !important; border: none !important; width: 100% !important; }
        .redirect-customizable { color: #A61816 !important; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important; }

  # OAuth Identity Providers
  GoogleIdentityProviderV3:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleOAuth
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      ProviderName: "Google"
      ProviderType: "Google"
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: "profile email openid"
      AttributeMapping:
        email: "email"
        name: "name"
        username: "sub"

  AmazonIdentityProviderV3:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasAmazonOAuth
    Properties:
      UserPoolId: !Ref CognitoUserPoolV3
      ProviderName: "LoginWithAmazon"
      ProviderType: "LoginWithAmazon"
      ProviderDetails:
        client_id: !Ref AmazonClientId
        client_secret: !Ref AmazonClientSecret
        authorize_scopes: "profile"
      AttributeMapping:
        email: "email"
        name: "name"
        username: "user_id"

  # =============================================================================
  # DNS - Route 53 Records
  # =============================================================================

  # SSL Certificate for Cognito Auth Subdomain (must be in us-east-1)
  AuthCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsProdEnvironment
    Properties:
      DomainName: !Sub "${AuthSubdomain}.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "${AuthSubdomain}.${DomainName}"
          HostedZoneId: !Ref HostedZoneId

  # Route 53 Record Set for EC2 (A record pointing to Elastic IP)
  DomainRecordSet:
    Type: AWS::Route53::RecordSet
    Condition: IsProdEnvironment
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      TTL: 300
      ResourceRecords:
        - !Ref EC2ElasticIP

  # Route 53 Record Set for Auth Subdomain
  AuthDomainRecordSet:
    Type: AWS::Route53::RecordSet
    Condition: IsProdEnvironment
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${AuthSubdomain}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CognitoDomainV3.CloudFrontDistribution
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  # S3 Buckets
  BackupBucketName:
    Description: S3 bucket for database backups (prod only)
    Value: !If [IsProdEnvironment, !Ref BackupBucket, "N/A (dev environment)"]

  # Cognito
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPoolV3

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolV3Client

  CognitoDomainURL:
    Description: Cognito Domain URL for hosted UI
    Value: !If
      - IsProdEnvironment
      - !Sub "https://${AuthSubdomain}.${DomainName}"
      - !Sub "https://${CognitoDomainV3}.auth.${AWS::Region}.amazoncognito.com"

  AdminGroupName:
    Description: Name of the admin group in Cognito User Pool
    Value: !Ref CognitoAdminGroupV3

  EditorGroupName:
    Description: Name of the editor group in Cognito User Pool
    Value: !Ref CognitoEditorGroupV3

  # DNS
  CustomDomainURL:
    Description: Website URL with custom domain (production only)
    Value: !If [IsProdEnvironment, !Sub "https://${DomainName}", "N/A (dev environment)"]

  AuthCertificateARN:
    Description: Auth subdomain ACM Certificate ARN (production only)
    Value: !If [IsProdEnvironment, !Ref AuthCertificate, "N/A (dev environment)"]

  # IAM (dev only - prod uses separate cocktaildb-prod-ec2 stack)
  EC2RoleArn:
    Condition: IsDevEnvironment
    Description: ARN of the EC2 IAM Role (dev only)
    Value: !GetAtt EC2Role.Arn

  EC2InstanceProfileName:
    Condition: IsDevEnvironment
    Description: Name of the EC2 Instance Profile (dev only)
    Value: !Ref EC2InstanceProfile
