AWSTemplateFormatVersion: '2010-09-09'
Description: CocktailDB EC2 Infrastructure (IAM Role, Instance Profile, Elastic IP)

# This stack manages EC2-specific AWS resources separately from the main stack.
# After migration is complete, these resources can be imported into the main stack
# using CloudFormation resource import.

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: The deployment environment

Resources:
  # =============================================================================
  # IAM Role and Instance Profile for EC2
  # =============================================================================

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub cocktaildb-${Environment}-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  # Analytics bucket
                  - !Sub arn:aws:s3:::cocktailanalytics-${AWS::AccountId}-${Environment}
                  - !Sub arn:aws:s3:::cocktailanalytics-${AWS::AccountId}-${Environment}/*
                  # Backup bucket (prod only, but safe to include for dev)
                  - !Sub arn:aws:s3:::cocktaildbbackups-${AWS::AccountId}-${Environment}
                  - !Sub arn:aws:s3:::cocktaildbbackups-${AWS::AccountId}-${Environment}/*
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: cocktaildb

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub cocktaildb-${Environment}-ec2-profile
      Roles:
        - !Ref EC2Role

  # =============================================================================
  # Elastic IP for stable DNS
  # =============================================================================

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub cocktaildb-${Environment}
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: cocktaildb

Outputs:
  EC2RoleName:
    Description: Name of the EC2 IAM Role
    Value: !Ref EC2Role
    Export:
      Name: !Sub ${AWS::StackName}-EC2RoleName

  EC2RoleArn:
    Description: ARN of the EC2 IAM Role
    Value: !GetAtt EC2Role.Arn
    Export:
      Name: !Sub ${AWS::StackName}-EC2RoleArn

  EC2InstanceProfileName:
    Description: Name of the EC2 Instance Profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-EC2InstanceProfileName

  ElasticIP:
    Description: Elastic IP address for the EC2 instance
    Value: !Ref ElasticIP
    Export:
      Name: !Sub ${AWS::StackName}-ElasticIP

  ElasticIPAllocationId:
    Description: Allocation ID of the Elastic IP
    Value: !GetAtt ElasticIP.AllocationId
    Export:
      Name: !Sub ${AWS::StackName}-ElasticIPAllocationId
