#!/bin/bash
# Generate a local development config.js that points to the dev API
# This allows testing frontend changes locally without deploying

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_PATH="$PROJECT_ROOT/src/web/js/config.js"
STACK_NAME="${1:-cocktail-db-dev}"

echo "🔧 Generating local development config..."
echo "Stack: $STACK_NAME"
echo ""

# Get dev API endpoint from CloudFormation
echo "📡 Fetching dev API endpoint from CloudFormation..."
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' \
    --output text)

# Get Cognito configuration
echo "🔐 Fetching Cognito configuration..."
USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
    --output text)

CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
    --output text)

COGNITO_DOMAIN=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomainURLV3`].OutputValue' \
    --output text)

# Check if we got all values
if [ -z "$API_URL" ] || [ -z "$USER_POOL_ID" ] || [ -z "$CLIENT_ID" ] || [ -z "$COGNITO_DOMAIN" ]; then
    echo "❌ Error: Could not retrieve all required configuration values"
    echo "API_URL: $API_URL"
    echo "USER_POOL_ID: $USER_POOL_ID"
    echo "CLIENT_ID: $CLIENT_ID"
    echo "COGNITO_DOMAIN: $COGNITO_DOMAIN"
    exit 1
fi

# Generate config.js for local development
echo "📝 Writing config.js..."
cat > "$CONFIG_PATH" << EOF
// Configuration for the Cocktail Database application (local development)
// This file is auto-generated by scripts/local-config.sh
// DO NOT COMMIT THIS FILE - it's for local development only

const config = {
    // API endpoint (dev environment)
    apiUrl: '$API_URL',

    // Cognito configuration (dev environment)
    userPoolId: '$USER_POOL_ID',
    clientId: '$CLIENT_ID',
    cognitoDomain: '$COGNITO_DOMAIN',

    // Application URL (local server)
    appUrl: 'http://localhost:8000',

    // General settings
    appName: 'Cocktail Database (local dev)'
};

// Export the configuration
export default config;
EOF

echo ""
echo "✅ Config generated successfully!"
echo ""
echo "📋 Configuration:"
echo "  API URL: $API_URL"
echo "  User Pool: $USER_POOL_ID"
echo "  App URL: http://localhost:8000"
echo ""
echo "🚀 Next steps:"
echo "  1. Start local server: ./scripts/serve.sh"
echo "  2. Open browser: http://localhost:8000"
echo "  3. Test your changes!"
echo ""
echo "⚠️  Remember: Don't commit config.js changes to git"
